from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
import textwrap
import os


def generate_pdf_document(topic: str, num_pages: int, content_data: list):
    """Generate multi-page PDF with different content on each page"""
    
    os.makedirs("files", exist_ok=True)
    
    import datetime
    filename = f"files/document_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4
    
    # Title page
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width / 2, height - 2 * inch, topic)
    
    c.setFont("Helvetica", 12)
    c.drawCentredString(width / 2, height - 2.5 * inch, f"Generated by Kurdish AI")
    c.drawCentredString(width / 2, height - 2.8 * inch, datetime.datetime.now().strftime("%B %d, %Y"))
    
    c.showPage()
    
    # Content pages
    for i, page_content in enumerate(content_data[:num_pages-1], 1):
        y_position = height - 1.5 * inch
        
        # Page title
        c.setFont("Helvetica-Bold", 16)
        title = page_content.get('title', f'Section {i}')
        c.drawString(1 * inch, y_position, title)
        y_position -= 0.5 * inch
        
        # Page content
        c.setFont("Helvetica", 11)
        points = page_content.get('points', [])
        
        for point in points:
            # Wrap text to fit page width
            wrapped_lines = textwrap.wrap(point, width=80)
            
            for line in wrapped_lines:
                if y_position < 1 * inch:
                    c.showPage()
                    y_position = height - 1.5 * inch
                    c.setFont("Helvetica", 11)
                
                c.drawString(1 * inch, y_position, f"• {line}")
                y_position -= 0.3 * inch
            
            y_position -= 0.2 * inch
        
        # Page number
        c.setFont("Helvetica", 9)
        c.drawCentredString(width / 2, 0.5 * inch, f"Page {i + 1}")
        
        c.showPage()
    
    c.save()
    print(f"✅ PDF saved: {filename}")
    return filename