from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os


def generate_word_document(topic: str, num_pages: int, content_data: list):
    """Generate multi-page Word document with different content"""
    
    os.makedirs("files", exist_ok=True)
    
    import datetime
    filename = f"files/document_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    
    doc = Document()
    
    # Set margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
    
    # Title page
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.add_run(topic)
    title_run.font.size = Pt(28)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(0, 51, 102)
    
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_run = subtitle.add_run(f"\nGenerated by Kurdish AI\n{datetime.datetime.now().strftime('%B %d, %Y')}")
    subtitle_run.font.size = Pt(12)
    subtitle_run.font.color.rgb = RGBColor(89, 89, 89)
    
    doc.add_page_break()
    
    # Content pages
    for i, page_content in enumerate(content_data[:num_pages-1], 1):
        # Section heading
        heading = doc.add_heading(page_content.get('title', f'Section {i}'), level=1)
        heading.runs[0].font.color.rgb = RGBColor(0, 51, 102)
        
        # Section content
        points = page_content.get('points', [])
        
        for point in points:
            p = doc.add_paragraph(point, style='List Bullet')
            p.paragraph_format.left_indent = Inches(0.25)
            p.paragraph_format.space_after = Pt(6)
        
        doc.add_paragraph()  # Spacing
        
        if i < len(content_data):
            doc.add_page_break()
    
    doc.save(filename)
    print(f"✅ Word document saved: {filename}")
    return filename